kwaroran/RisuAI

src/lib/SideBars/Settings.svelte, src/ts/database.ts, src/ts/process/stableDiff.ts
add Upscaler On/Off and Upscaler setting. and hide SD setting when SD option disabled.
=> enable Upscaler option and hide SD setting.

src/lib/SideBars/Settings.svelte
this select class replaced to toggle class that under this class already.
=> remove unused code.

src/lib/SideBars/BarIcon.svelte, src/lib/SideBars/Sidebar.svelte, src/lib/SideBars/SidebarAvatar.svelte, src/lib/SideBars/SidebarIndicator.svelte, src/lib/UI/BaseRoundedButton.svelte, src/ts/characters.ts
This PR introduces several modifications to enhance the UI and code structure. Here are the details:
1. Added SidebarIndicator to improve the sidebar navigation experience.
2. Removed the BarIcon components from the Character at Bar. They have been replaced with the SidebarAvatar component. This change aims to refactor the BarIcon into UI components (TODO: Implement the UI component refactor and sidebar state flow)
3. Update shape and color of NewCharButton 
4. ~~Refactored the getCharImage function by removing unused code, improving code cleanliness and maintainability.~~
* Reverted. Because, it's in use in so many places that it's probably too big a scope to cover in this PR.
These changes aim to improve the UI and code structure. The Avatar UI has been updated to a circular shape, but …
=> feat(sidebar-avatar): Creat SidebarIndicator & Refactor Sidebar UI

src/lib/ChatScreens/Suggestion.svelte, src/lib/Setting/Pages/BotSettings.svelte, src/lib/Setting/Settings.svelte, src/lib/SideBars/CharConfig.svelte
- [ - ] Did you check if it works normally in all models? *ignore this when it dosen't uses models*
- [ O ] Did you check if it works normally in all of web, local and node hosted versions? if it dosen't, did you blocked it in those versions?
- [ O ] Did you added a type def?
There are many users who can't find the character deletion, so it has been changed so that it is clearly visible in the header.
It is inconvenient to scroll up and close the long settings window when scrolling, so it is fixed at the top.
Modify tokens count position not moved together auto suggest prompt.
Fixed the problem that auto-suggestion does not work for firstMessage
Fixed the problem that auto-suggestion is not saved
=> [UX] settings close floating button, fix tokens position auto suggest prompt, AutoSuggest minor bugs

src/lib/UI/Hub.svelte
=> [fix] hub page button not showing/working

.github/workflows/github-actions-builder.yml
=> [fix] changed to workflow_dispatch

src/lib/Setting/Pages/BotSettings.svelte
=> *PLEASE* Update BotSettings.svelte

src/lang/en.ts, src/lib/Setting/Pages/BotSettings.svelte, src/ts/process/stringlize.ts
=> Merge from Main

src/ts/process/stringlize.ts
=> Remove some oobabooga stop strings

src/main.ts
=> simple commit for cloudflare

src/ts/process/request.ts
An error occurred when use gemini-pro model with disabled Vertex-AI:
=> [fix] iterable error when use gemini-pro

src/ts/process/request.ts
=> Fix aws claude

src/lib/Setting/Pages/OtherBotSettings.svelte, src/ts/process/stableDiff.ts, src/ts/storage/database.ts
- [ v ] Did you check if it works normally in all models? *ignore this when it dosen't uses models*
- [ v ] Did you check if it works normally in all of web, local and node hosted versions? if it dosen't, did you blocked it in those versions?
- [ v ] Did you added a type def?
=> Code updates due to NAID API changes and feature additions.

.github/workflows/github-actions-builder.yml
=> Update GitHub Actions workflow to trigger on push to production branch

src/ts/process/request.ts
=> Refactor return value of requestChatDataMain function

src/lib/Setting/Pages/BotSettings.svelte, src/ts/process/request.ts
=> add aws claude-3

src/lib/UI/GUI/MultiLangInput.svelte
=> Make language selection to not display unknown languages

src/lib/Setting/Pages/BotSettings.svelte, src/ts/process/request.ts
=> add aws claude haiku

src/etc/patchNote.ts, src/lib/ChatScreens/Chat.svelte
=> 1.86.0 minor fixes

src/lang/cn.ts, src/lang/de.ts, src/lang/en.ts, src/lang/ko.ts, src/lang/vi.ts, src/lib/Setting/Pages/LanguageSettings.svelte, src/ts/process/tts.ts, src/ts/storage/database.ts, src/ts/translator/translator.ts
DeepLX 구현까지 성공한 커밋입니다. 노드 버전은 Failed to Fetch떄문에 못해보고
타우리에서는 정상 구동되었습니다.
=> deeplX function added

src/lib/ChatScreens/DefaultChatScreen.svelte
=> Revert loadpages behavior dude to bugs

src/ts/storage/globalApi.ts
=> Refactor tab activation handling in saveDb function

src/ts/storage/globalApi.ts
=> Update BroadcastChannel name in globalApi.ts

src/ts/storage/globalApi.ts
=> Fix BroadcastChannel reference in globalApi.ts

src/ts/process/request.ts
=> add aws opus

src/lib/Setting/Pages/OobaSettings.svelte, src/ts/storage/database.ts
=> Fix Oobamode

src/lib/UI/MainMenu.svelte
=> Add border color in update alert in MainMenu.svelte

.github/workflows/github-actions-builder.yml
=> Add support for macOS platform in GitHub Actions workflow

src/preload.ts
=> Fix hostname cond

src/lib/UI/MainMenu.svelte
=> Update MainMenu.svelte to display patch update notification

src/ts/process/memory/hanuraiMemory.ts
This pr fixes the bug in the issue #399 
I think it's a bug that needs to be fixed regardless of what we discuss in the issue, so I send a pull request before we discuss it.
=> Fix hanurai to skip query chats when push to processor

src/lib/Others/GithubStars.svelte
=> refactor: Update email address in GithubStars.svelte

src/lib/Setting/Pages/OtherBotSettings.svelte, src/ts/process/index.ts, src/ts/process/memory/hypav2.ts, src/ts/storage/database.ts
=> Feat: HypaV2

src/lib/Setting/Pages/OtherBotSettings.svelte
=> feat: Update memory options in OtherBotSettings

src/lib/Setting/Pages/OtherBotSettings.svelte
=> feat: Correct typo in OtherBotSettings.svelte and update memory options

src/lib/SideBars/CharConfig.svelte, src/ts/characterCards.ts, src/ts/realm.ts
=> Fix realm behavior

src/ts/tokenizer.ts
=> feat: Add support for Cohere AI model in tokenizer

src/ts/characterCards.ts
=> fix low level access

package.json
=> Fix: cloudflare build

package.json, pnpm-lock.yaml
=> Update build dependencys

src/lib/Setting/Pages/Module/ModuleSettings.svelte
=> fix: fix module removal removing incorrect module

src/ts/process/stableDiff.ts
=> feat: add quality parameter for DALL-E image generation

src/ts/drive/backuplocal.ts
Fix https://github.com/kwaroran/RisuAI/issues/475
=> Fix Local Backup Loading Failure Due to Incorrect Backup Data Saving.

src/ts/plugins/automark.ts
=> fix:highlight

src/lib/Others/AlertComp.svelte
=> refactor: Update AlertComp.svelte to fix export button alignment

src/ts/characterCards.ts
=> refactor: Fix bug in characterCards.ts

src/ts/translator/translator.ts
=> Add "button" to the combine translation blacklist

.github/workflows/github-actions-builder.yml, .gitignore, src-tauri/Cargo.lock, src-tauri/Cargo.toml, src-tauri/tauri.conf.json
=> chore: add updater workflow

.github/workflows/github-actions-builder.yml
=> feat: Fix shell syntax error in GitHub Actions workflow

.github/workflows/github-actions-builder.yml
=> refactor: Update GitHub Actions workflow to support multiple platforms

.github/workflows/github-actions-builder.yml
=> fix GitHub Actions workflow to use matrix settings for runs-on

package.json, src/ts/stores.ts
=> Fix web error

package.json, src/ts/storage/accountStorage.ts
=> change vite

src/main.ts, src/ts/stores.ts
=> Add Try-catch on init

src/ts/storage/database.ts
=> move important vars on top

src/ts/process/lua.ts
=> refactor: Remove console.log statements and error alerts in lua.ts

src/ts/parser.ts
While implementing a specific behavior through CBS, I encountered limitations during handling first message. Therefore, I aim to modify the effect of certain keywords to accommodate a broader range of cases. The changes have been tested and presented no issues. However, I kindly request your review from a structural design perspective to ensure adequacy.
=> Refactor 'lastcharmessage' cbs

src/lib/ChatScreens/Chat.svelte
=> fix hideiconstore

src/ts/process/lua.ts
All of these functions were not working since it needs a special trick to call javscript async function within lua: https://github.com/ceifa/wasmoon/issues/22
The proper trick for allowing async function was added.
Also added missing awaits for similarity search.
You can use following lua trigger to test out the behaviour:
```lua
listenEdit("editOutput", function(triggerId, data)
local res = similarity(triggerId, data, {"happy", "angry", "sad"}):await()
return res[1]
end)
```
Note you need https://github.com/kwaroran/RisuAI/pull/572 to test this out since low level access is disabled for lua right now.
=> Fix bugs on lua simpleLLM, LLMMain, similarity, generateImage

src/ts/parser.ts, src/ts/process/scripts.ts
With the recent increased utilization of custom styles, I've modified the '{{chat_index}}' and '{{roll}}' cbs to cover a bit more cases. Please review them to see if they meet your vision.
=> Extend case for chat index and role

src/ts/process/triggers.ts
There appears to be a minor mistake here.
=> add missing break line

src/ts/translator/translator.ts
I'm sorry to repeat it so many times, but I think this is really the last time
=> Skip audio, video tag in combine translation feature

src/ts/process/request.ts
=> Fix reverse_proxy claude error

src/lib/SideBars/CharConfig.svelte, src/ts/process/tts.ts, src/ts/storage/database.ts, src/ts/translator/translator.ts
- [ v ] Did you check if it works normally in all models? *ignore this when it dosen't uses models*
- [ v ] Did you check if it works normally in all of web, local and node hosted versions? if it dosen't, did you blocked it in those versions?
- [ v ] Did you added a type def?
Add connection Gpt-SoVITS Api to ngrok turnel.
ttsReadOnlyQuoted support to japan Quote (「」)
and change google translate api language to auto (experiment)
=> Add Gpt-SoVITS TTS, change google translate lang to auto

server/node/server.cjs, src/lib/Setting/Pages/LanguageSettings.svelte, src/lib/Setting/Pages/OtherBotSettings.svelte, src/lib/SideBars/CharConfig.svelte, src/ts/process/index.ts, src/ts/process/tts.ts, src/ts/storage/database.ts, src/ts/translator/translator.ts
- [ v ] Did you check if it works normally in all models? *ignore this when it dosen't uses models*
- [ v ] Did you check if it works normally in all of web, local and node hosted versions? if it dosen't, did you blocked it in those versions?
- [ v ] Did you added a type def?
Update GPT-SoVITS fetch, support Auto path and long audio file
Google translator input language select support
User now can Choice auto read tts when send chat completed
=> Update GPT-SoVITS fetch, support Auto path and long audio file. Google Translator lang select update

src/lib/UI/GUI/SideBarArrow.svelte
=> Fix sidebar arrow disappearing

src/ts/process/request.ts
=> Fix max tokens

src/ts/translator/translator.ts
현재 로컬 리스 번역은 경우의수를 충분히 고려하지 않아 번역에 문제가 있습니다. 로컬 리스의 번역 로직을 웹 버전과 동일하게 변경하고 싶습니다.
A translation issues in current local environment because cases are not sufficiently considered. I want to change local translation logic alike web version.
=> Disable LLM translation using DOM parser

src/ts/characterCards.ts
Testing conducted in both Node environments.
Due to some Tauri code under development, testing was performed on a previous commit before rewriting.
Add Import URLs for characters, modules, presets, etc., to RisuAI.
These URLs can be used for purposes such as shortening when sharing character files, aiming to minimize external leakage of character files.
It seems like it could be useful in character card sharing communities.
Due to the large size of import files, a CORS proxy was not used, but it could be added if required.
=> Add File Import URL

.dockerignore, Dockerfile, README.md, docker-compose.yml
This PR introduces two main changes:
1. Adds Docker support to the RisuAI project, making it easier for users to deploy and manage the application in a containerized environment. This is particularly useful for those who want to host the web version of RisuAI.
2. Improves the README file:
- Enhances the readability of the screenshots table
- Corrects spelling and grammar issues in the Features section
- Improves overall formatting and consistency
Run the following command in the root directory:
```shell
docker-compose up -d
=> Support Docker and improve README.md

src/ts/characterCards.ts
- After uploading the character file to GitHub, conducted tests in both the RisuAI web and Node environments.
- Fixed the bug where the character list was not updating in certain situations after importing a URL.
- Removed the hash after import to prevent the same character from being imported again upon refresh.
- Added exception handling for import file downloads.
=> Fixed bugs related to URL file import and improved usability

src/ts/process/request.ts
=> add aws 3.5 sonnet v2

src/ts/process/files/image.ts, src/ts/process/request.ts
This PR fixes the image input functionality for the Gemini model.
The previous implementation attempted to process images in the following way:
1. In the `OpenAIChat` type, if the `memo` field started with `inlayImage`, the `content` field's value was copied into a variable called `pendingImage`.
2. Later, if the `chat` role was `'user'` and `pendingImage` was not an empty string, the code processed the image.
However, it does not seem to work as expected in the current state.
I updated the image input handling to align with the method used in RisuAI for handling GPT’s image input. Specifically, the changes include:
1. In `image.ts`, I explicitly specified the `gemini-exp` model.
2. If the `chat` object has a `multimodals` field and the `role` is `user`:
- I created an array called …
=> Fix Gemini Image Input Functionality

.github/pull_request_template.md
- It's just a change in the document (native language).
Fixed typo & changed the tone of the PR template, with the help of Copilot.
=> :pencil2: Fix typos and tones of the pr template

src/ts/process/memory/hypav2.ts
Emergency fix of PR #680, #696 
Source of problem: Every time when a chat is sent with HypaV2 active, it always appended HypaAllocatedToken amount of tokens to the currentTokens.
This did not get subtracted at the end, even though this is nothing more than a virtual limit like the output tokens.
=> Fix: Token counting fix

src/lang/en.ts, src/lang/ko.ts, src/lib/SideBars/Sidebar.svelte, src/lib/SideBars/SidebarAvatar.svelte, src/ts/globalApi.svelte.ts, src/ts/storage/database.svelte.ts
This PR adds a new feature that allows users to add custom images to character folders. Instead of uploading images directly, this feature utilizes the existing image pool from **the global module**. Users can either select from existing images in the global module or upload new images to the module.
The users can use a context menu on a folder to update its image.
The global module was chosen for several reasons:  
1. It allows the reuse of existing functions and code, minimizing the need for new implementations.  
2. Users can easily select existing images without re-uploading them.  
3. The global module provides reliable support for image upload and deletion.  
4. Images uploaded via the global module are accessible across all platforms where the shared data is available.
To retrieve …
=> Add Custom Character Folder Image Feature Using Global Module Assets

src/ts/process/memory/hypav2.ts
This PR addresses several issues in the HypaV2 memory system:
1. Improved Summarization Error Handling
- Before: When unable to summarize messages while exceeding context size, HypaV2 would continue and make API requests with unintentionally truncated context
- After: HypaV2 now provides clear error messages asking users to adjust their settings when:
- Unable to summarize last 4 messages
- A single message exceeds chunk size
2. Message Order Preservation
- Before: lastTwoChats logic was causing the first message (index 1) and user input (index 2) to appear in the wrong order
- After: Fixed by adjusting the initial index to preserve the original message sequence
3. Message Filtering
- Added logic to skip unnecessary messages during summarization:
- Excludes [Start a new chat] message at …
=> fix: Fix message handling and summarization in HypaV2

src/ts/globalApi.svelte.ts
EN
fix non-tauri environment backup issue. (e.g. backwards reset issue)
fix applying duplicate backup file.
KR
Tauri 환경(로컬리스)가 아닌 상황에서 과거 20개의 백업본 이외에 나머지 백업본을 저장하지 않던 문제를 수정합니다. (뒤로가기 이슈)
백업본 적용 시 모든 백업본을 적용해보던 로직을 개선합니다.
=> fix backup in non-tauri environment

src/lib/Setting/Pages/OtherBotSettings.svelte
This calculation provides users with an approximate maximum memory tokens ratio, allowing users to choose appropriate maximum context size or memory tokens ratio based on their specific needs and circumstances.
The maximum memory tokens ratio is calculated based on:
`maxMemoryRatio = (maxContextTokens - requiredTokens) / maxContextTokens`
- where `requiredTokens = promptTemplateTokens + charTokens + maxLoreTokens + (maxResponseTokens * 3)`
=> feat: display estimated max memory tokens ratio in HypaV3 settings

src/lib/Setting/Pages/Module/ModuleMenu.svelte, src/lib/SideBars/CharConfig.svelte, src/lib/SideBars/SideChatList.svelte, src/ts/process/modules.ts
This PR allows custom toggles to be added in the module as well. Below is a screenshot of the updated module editing UI. Please feel free to let me know if any further adjustments are needed or if you prefer not to proceed with these changes.
=> feat: custom toggles for modules

src/lib/Setting/Pages/OtherBotSettings.svelte, src/ts/process/memory/hypamemory.ts, src/ts/storage/database.svelte.ts
This PR introduces support for OpenAI-compatible embedding API
=> feat: add support for OpenAI-compatible embedding API

src/ts/model/modellist.ts, src/ts/process/request.ts
This PR aims to enable the use of the newly added claude 3.7 sonnet model (and some legacys (¬‿¬)) on AWS.
=> feat: aws sonnet 3.7 + legacy

src/lib/ChatScreens/Chat.svelte, src/lib/ChatScreens/ChatScreen.svelte, src/lib/ChatScreens/DefaultChatScreen.svelte, src/ts/util.ts
Enhance chat application efficiency by implementing caching for markdown parsing and message forms, along with lazy loading and virtual scrolling for improved performance in large chat histories. Introduce a cleanup mechanism for cache management.
=> Optimize chat rendering and performance with caching and lazy loading

src/lib/SideBars/SideChatList.svelte
existing character chat folder
기존 캐릭터에 폴더 추가 안되는 것을 수정하는 PR입니다.
=> fix: 기존 캐릭터에 폴더 추가 안되는 것 수정

src/ts/parser.svelte.ts
It would be convenient if there was a cbs like this when handling module assets. Thanks for your time.
=> feat:Add 'module_assetlist' cbs

package.json, pnpm-lock.yaml, public/assets/bergamot-translator-worker.js, public/assets/translator-worker.js, src/lang/cn.ts, src/lang/de.ts, src/lang/en.ts, src/lang/es.ts, src/lang/ko.ts, src/lang/vi.ts, src/lang/zh-Hant.ts, src/lib/Setting/Pages/LanguageSettings.svelte, src/ts/storage/database.svelte.ts, src/ts/translator/bergamotTranslator.ts, src/ts/translator/translator.ts, vite.config.ts
Translation is performed using the models hosted in the repository:
https://github.com/mozilla/firefox-translations-models/
When the translation is first running, the model is downloaded from the repository.
Testing completed for `npm dev` and Node server environment.
=> Add Firefox(Bergamot) local translation

src/ts/process/scripts.ts
=> Revert "refactor: regex caching"

src/ts/process/scripts.ts
=> Revert "Revert "refactor: regex caching""

src/ts/tokenizer.ts
Previous PR #805 had a bug due to incorrect flow of if statements. I apologize for this.
In this PR, I have improved the flow of if statement additionally from the modification I made before.
Please refer [Fix: Correct tokenize flow in tokenizer encode function](https://github.com/kwaroran/RisuAI/commit/09228f3f867a2f05b24e5bf1163ab743e3913894) To see the how I changed the flow.
The biggest change of this commit is that it resolves the issue of duplicate tokenization that was occurring
By add a `Line 122: if (result === undefined) {`
I think this change corrected the error even if people didn't turn on the caching option.
And there is an error in the tikJS function, independent of this wrong flow.
https://github.com/dqbd/tiktoken/issues/35
=> Add: Caching tokenize

src/lib/Setting/Pages/Module/ModuleMenu.svelte, src/lib/SideBars/LoreBook/LoreBookList.svelte, src/ts/process/lorebook.svelte.ts
This PR adds sorting, import, and export functionality to the Module Lorebook list.
I focused on preserving the existing code structure as much as possible while implementing these changes.
Thank you for your time and review!
=> feat: module lorebook sort, import, export

pnpm-lock.yaml
=> Fix ERR_PNPM_OUTDATED_LOCKFILE

src/ts/process/lua.ts
This PR adds read-only persona name and description access from Lua by adding `getPersonaName(triggerId)` and `getPersonaDescription(triggerId)`. The description is parsed before returning.
=> feat: Open read-only access to persona name/desc from Lua

src/lib/Others/HypaV3Modal.svelte, src/lib/Playground/PlaygroundEmbedding.svelte, src/lib/Setting/Pages/OtherBotSettings.svelte, src/ts/process/memory/hypamemory.ts, src/ts/process/memory/hypav3.ts, src/ts/process/transformers.ts
- fix: pass message index when processing regex script in HypaV3 Modal
- feat: add BGE-m3-ko embedding
=> fix: improve HypaV3 Modal

src/lib/Others/AlertComp.svelte
- Make only markdown content scrollable while keeping OK button visible
=> fix: improve scrolling in Show Request Logs

src/ts/process/lua.ts
This PR adds ~~two~~ one function: ~~`getDescription()` for character description, and~~ (See #852)`getAuthorsNote()` for author's note.
It also removes `LuaSafeIds.has(id)` from most reader functions without any side effects. Since `getFullChatMain()` has no such check already and everything else should be lighter than `getFullChatMain()`, I think it'll be fine.
=> feat: Allow more data to be readable from Lua in editDisplay step

src/lib/SideBars/LoreBook/LoreBookList.svelte, src/ts/model/modellist.ts
In my previous PR #822 there's an issue where the module lore sort was not saving properly. I believe this PR will fix that. I appreciate your time.
=> feat: aws claude 4 && fix: module lore sort properly

src/ts/process/lua.ts
Getting one single chat at a specified index would help lighten Lua scripts in certain scenarios such as "get the second last chat".
Currently I have to iterate (in `getFullChatMain`) the whole chat by `getFullChat(id)` and then `fullChat[#fullChat - 1]`. With this PR, it is simplified as `getChat(id, -2)`
Returns `nil` when no chat exists in the index.
=> feat: Allow getting one chat at an index

src/lib/SideBars/Scripts/TriggerList2.svelte
- Separated right-click menu functions from main trigger component
- Added dynamic positioning to prevent context menu from going off-screen
- Context menu now adjusts direction based on click position
=> Improve Trigger V2 context menu positioning and code organization

src/lib/ChatScreens/Chat.svelte
Dear Developer,
Thank you for your amazing service.
Last year, I submitted a log generator code, and I was pleased to see it was implemented in the log copy-paste functionality. I apologize for not providing improved code since then.
This time, I have made significant design improvements to enhance the visual appearance. I expect this will improve the overall UX.
The modified file path is as follows:
src/lib/ChatScreens/Chat.svelte
Please check 'Chat.svelte'
This PR significantly improves the chat copy functionality by implementing a modern, professional HTML template for copied messages, replacing the basic layout with a card-based design.
- Modern Card Design: Replaced simple vertical layout with elegant card-style template
- Professional Typography: Implemented Segoe UI, Roboto, Arial …
=> Enhanced Chat Copy Feature with Modern HTML Template

src/lang/cn.ts, src/lang/de.ts, src/lang/en.ts, src/lang/es.ts, src/lang/ko.ts, src/lang/vi.ts, src/lang/zh-Hant.ts, src/lib/Setting/Pages/PersonaSettings.svelte, src/lib/Setting/listedPersona.svelte, src/ts/persona.ts, src/ts/storage/database.svelte.ts
Adds a new 'Note' section to the Persona editing page. The note shows up alongside the name in the Persona selection window, but does not affect the chat or prompt in any way, allowing for a new method of discriminating different personas with the same name.
=> Add note to persona

src/lib/Setting/Pages/Module/ModuleMenu.svelte, src/lib/SideBars/CharConfig.svelte
This PR relocates two settings to more intuitive locations.
*   **Background Embedding:** Moved from Advanced Settings to the Script section for both the module and Charconfig. It is now located above the regex script, as it is considered more integral to scripting than a general advanced option.
*   **Bias:** Moved from the Script menu to Advanced Settings in Charconfig. The bias setting is a more fundamental configuration parameter, making it a better fit for Advanced Settings.
=> Refactor: Relocate settings for better organization

src/lib/Setting/Pages/BotSettings.svelte, src/ts/model/modellist.ts, src/ts/process/mcp/risuaccess.ts, src/ts/process/request/google.ts, src/ts/storage/database.svelte.ts
This PR addresses critical issues in the Vertex AI integration and introduces new configuration options. I also refined the risuaccess MCP server and Google Cloud requests to improve MCP compatibility.
- Fixed Incorrect Request URL: I corrected the Vertex AI request URL, which was previously misdirected to a generic Google Cloud endpoint. This happened because the model format was missing from the request.
- Resolved Access Token Error: I've patched a bug in the Vertex AI access token issuance process. There was a type error.
- Added Configuration Options: You can now specify your Vertex Project ID and Vertex Region directly within the model settings.
- Renamed MCP Tool Parameters: The 'in' and 'out' parameters for the risu-set/add-character-regex-scripts MCP tools are now 'regIn' and …
=> Fix: (VertexAI) Correct API requests and authentication + MCP compatibility

src/ts/process/request/google.ts
This pull request resolves a key issue in the Google AI API integration, improving function calling reliability and performance. It enables support for parallel function calls and refactors the associated code for clarity.
Previously, when a model used a function, the follow-up API request was built incorrectly. It omitted the model's text output that preceded the function call, sending only the `user-input -> model-function-call -> user-function-response`, instead of `user-input -> model-text-output -> model-function-call -> user-function-response`. This lack of context resulted in unnatural conversations and poor tool performance.
Additionally, this flawed logic caused two critical errors:
1.  A `500 Internal Server Error` occurred when the model attempted parallel function calls, as …
=> fix(google): Correct Function Calling Context and Enable Parallel Tool Use

src/ts/process/scriptings.ts
Adds `upsertLocalLoreBook(triggerId, name, content, options)` to Lua API. This allows Lua to dynamically add or update chat-local lore books.
Global or module lore books are not within the scope of this PR and I have no plan to do so.
The `options` object shape is different from `loreBook` type so that changes to the type won't result in userland breakages.
=> feat: Upsert local lore books from Lua

src/ts/process/triggers.ts
This PR fixes an issue where CBS parsing was not being applied correctly to the Array, resulting in malformed data. The logic has been adjusted to ensure proper application.
=> Fix: Correct CBS parsing for Array in v2trigger

.github/workflows/docker-build.yml
- ghcr test finished
Hi there.
Adding the 'latest' tag ensure consistency in the documentation and guides, even as new versions are released.
=> ci: push 'latest' tag to ghcr

src/lang/cn.ts, src/lang/de.ts, src/lang/en.ts, src/lang/es.ts, src/lang/ko.ts, src/lang/vi.ts, src/lang/zh-Hant.ts, src/lib/SideBars/LoreBook/LoreBookData.svelte, src/lib/SideBars/LoreBook/LoreBookList.svelte, src/ts/characterCards.ts
1. Modify folder renaming logic
Real-time modifications such as lorebook
2. Improved folder deletion
Delete the entire lorebook when deleting folders (need to confirm two warning windows)
3. Move lorebook to folder
Now we can move the lorebook to the folder, and the opposite is possible
++ fix: lorebook import twice when importing charX
=> lorebook folder Improvements

src/lib/SideBars/CharConfig.svelte
Adds up/down buttons to reorder First Messages, as requested by the community. This allows for easier management of message priority.
=> Feat: Add reordering buttons for First Messages

src/lib/SideBars/Scripts/TriggerList2.svelte
This PR resolves an issue where the scroll position in the RisuAI v2trigger menu would reset upon internal navigation.
With this fix, the scroll position and the last selected trigger are now preserved when returning to the menu. This maintains the user’s context and improves the overall navigation experience.
=> Fix: Preserve scroll state in v2trigger menu

src/lang/en.ts, src/lang/ko.ts, src/lib/ChatScreens/Chat.svelte, src/lib/ChatScreens/DefaultChatScreen.svelte, src/lib/Setting/Pages/DisplaySettings.svelte, src/ts/storage/database.svelte.ts
=> Feat: Add page indicator for swipe reroll in first message

src/lib/Setting/Pages/LanguageSettings.svelte
Added Persian (Farsi) as translator language, suggested in [official Discord server](https://discord.com/channels/1108412316619391006/1396245731173466265).
=> feat: Support Persian (Farsi) as Google Translator lang

src/ts/process/request/google.ts
- Added checks for missing Vertex AI authentication details (client email and private key).
- Added a check for the availability of the Web Crypto API (crypto.subtle) before using importKey.
- These changes should prevent 'Cannot read properties of undefined (reading 'importKey')' errors by ensuring necessary prerequisites are met or by providing clearer error messages.
- Added a hint to the Web Crypto API error message, suggesting HTTPS might be required.
=> fix: Enhance Vertex AI authentication and Web Crypto API error handling

src/ts/process/memory/hypav3.ts
Filter Thoughts block from hypav3 summary
=> fix: filter Thoughts from hypav3 summary

src/ts/model/modellist.ts, src/ts/process/index.svelte.ts, src/ts/process/request/google.ts
Add gemini-2.5-flash-image-preview model
(This model does not support thinking)
Fixed an unexpected behavior on edge-cases (image-only responses)
=> add: gemini 2.5 flash image preview

.gitignore, README.md
- Update Svelte badge to version 5, Typescript to 5.6, and Tauri to 2.5
- Add features description (Gemini, DeepInfra APIs, Long-term Memory)
- Link formatting for discord
- Updated .gitignore to exclude .qoder/*
=> docs(readme): update badges and add features description

src/ts/drive/backuplocal.ts
- Fixes a TypeError when local backup encounters null asset data, preventing the process from crashing.
- Implements real-time and final summary reporting for skipped assets during backup.
- Uses user-friendly asset and character names in reports.
- Consolidates final success/failure alerts into a single summary dialog.
=> feat: Improve local backup robustness and UX

src/lib/ChatScreens/Chat.svelte, src/ts/cbs.ts, src/ts/parser.svelte.ts, src/ts/process/triggers.ts, src/ts/stores.svelte.ts
This PR introduces support for the risu-id attribute on HTML elements, enabling triggers to identify which specific element triggered their execution. This enhancement allows for more sophisticated and context-aware trigger behaviors.
- HTML elements can now include a risu-id attribute alongside risu-trigger
- New trigger_id placeholder available within triggers to access the clicked element's ID
- Enhanced trigger system to pass element identification data through the execution pipeline
- Added CurrentTriggerIdStore for managing trigger ID state across execution contexts
- Implemented trigger_id CBS function with proper normalization support (triggerid alias)
- Updated runTrigger function to accept and manage triggerId parameter
- Modified Chat.svelte to extract risu-id attribute and …
=> Add: risu-id Attribute Support for Enhanced Trigger Element Identification
