src/lang/cn.ts, src/lang/en.ts, src/lang/ko.ts, src/lib/ChatScreens/Chat.svelte, src/lib/Setting/Pages/DisplaySettings.svelte, src/ts/storage/database.ts
- [ - ] Did you check if it works normally in all models? *ignore this when it dosen't uses models*
- [ O ] Did you check if it works normally in all of web, local and node hosted versions? if it dosen't, did you blocked it in those versions?
- [ O ] Did you added a type def?
- Added 'copied' string to language translation in multiple translations file.
- Added 'CopyIcon' to svelte import.
- Defined a new status message variable in Chat.svelte.
- Created a new function 'setStatusMessage' to display the current panel's state after certain action.
- Added a new setting 'useChatCopy' in 'DisplaySettings.svelte'.
- Created a checkbox with label 'useChatCopy' to toggle the Chat message copy.
- Integrated Clipboard API in Chat code to handle chat message copy via button click.
=> [UI/UX] Add copy chat message feature in Chat panel and enable usage in 'use chat copy' setting.

src/lib/ChatScreens/DefaultChatScreen.svelte
- [v] Did you check if it works normally in all models? *ignore this when it dosen't uses models*
- [NO] Did you added a type def?
send message double time by enter when writing korean. 
This issue occurs when input's composition is not end. 
https://github.com/kwaroran/RisuAI/assets/60877502/758b3168-d63c-4b64-8ca0-6a5afefad749
block send message when event is composing.
=> [fix] send message double time by enter when input's composition is not end

src/lib/Setting/Pages/BotSettings.svelte, src/lib/UI/ModelList.svelte, src/ts/process/index.ts, src/ts/process/request.ts
- The commit updates AI model settings for GPT-3.5 by allowing up to 4000 tokens for context size. It also adds a new option for GPT-3.5 Turbo 16k with a maximum context of 16000 tokens. Additionally, the commit limits the context size when exceeding the maximum limit for each model.
=> [feat] Update AI model settings for GPT-3.5 and add GPT-3.5 Turbo 16k option

src/ts/plugins/plugins.ts
- [ unrelated ] Did you check if it works normally in all models? *ignore this when it dosen't uses models*
- [ unrelated ] Did you check if it works normally in all of web, local and node hosted versions? if it dosen't, did you blocked it in those versions?
- [ unrelated ] Did you added a type def?
There were some missing break statements in the switch statement in plugins.ts.
=> Added missing break statements in switch statement in plugins.ts

src/ts/process/request.ts
I am running local llama in own API server. In streaming mode, the `Content-Type` is sometimes appended with something like `text/event-stream; charset=UTF-8`, so we just need to make sure the header contains the string `text/event-stream`.
=> Fixed event stream header check

src/ts/process/request.ts
Apply plain fetch option when use Streaming
=> [fix] apply plain fetch option when use Streaming

src/ts/translator/translator.ts
Fixed an error that caused VOICEVOX TTS to not output properly due to translation errors.
=> fix VOICEVOX transelate

src/lib/SideBars/CharConfig.svelte
Signed-off-by: hashcoko <hashcoko@gmail.com>
- [ v ] Did you check if it works normally in all models? *ignore this when it dosen't uses models*
- [ v ] Did you check if it works normally in all of web, local and node hosted versions? if it dosen't, did you blocked it in those versions?
- [ v ] Did you added a type def?
=> Fixed a bug where checking an inlay in the emotion bot would delete all assets.

src/ts/process/tts.ts
breaks statement was missed in 'openai' tts case.
It makes a bug that requesting openai TTS and novelai TTS both.
This commit will fix this issue.
=> Add missed break statement

src/ts/process/request.ts
- [✓] Did you check if it works normally in all of web, local and node hosted versions? if it dosen't, did you blocked it in those versions?
Now Oobabooga mode uses instruct mode when they request to server, but in the request code it still uses v1/chat/completions when request to server, which cause error when use it. After I change that part to v1/completions, it works well for me.
=> Fix errors when use Oobabooga mode

src/lib/Setting/Pages/OobaSettings.svelte, src/ts/model/ooba.ts, src/ts/tokenizer.ts
I write simple changes on code, which allow user to choose tokenizers.
As I write on https://github.com/kwaroran/RisuAI/issues/280, differences in tokenizers makes error when use mistral based models.
As I'm not good at javascript, I simply implement this work by write name of tokenizer model, and select one on tokenizer.ts file.
I test it on my node RisuAI and I send long context to my own server.
As result, ooba returned 15858 as prompt tokens.
And as I test on official tokenizer implementations, it shows 1k differences between llama tokenizer and mistral tokenizer.
So I think adding this option will help users use oobabooga with less error.
=> Add selectable tokenizer supports on Ooba

src/lib/UI/ModelList.svelte, src/ts/process/request.ts
Reference: 
https://platform.openai.com/docs/models/gpt-3-5-turbo
https://platform.openai.com/docs/deprecations
1. Added gpt-3.5-turbo-0125 model: The current gpt-3.5-turbo is pointed to the 0613 model, but the official documentation says it will automatically upgrade to the 0125 model on February 16 anyway.
2. Fixed the model name of gpt-4-0314, although it is deprecated.
=> Add gpt-3.5-turbo-0125, fix gpt-4-0314

src/ts/plugins/embedscript.ts
It seems like someone is holding breath for this.
=> add charjs apis for bgembed

package.json, src/lang/cn.ts, src/lang/de.ts, src/lang/en.ts, src/lang/ko.ts, src/lang/vi.ts, src/lib/ChatScreens/AdvancedChatEditor.svelte, src/lib/ChatScreens/DefaultChatScreen.svelte, src/lib/Setting/Pages/DisplaySettings.svelte, src/ts/storage/database.ts
I have added an editor and settings that highlight asterisks, quotes, and backticks, similar to AutoMark, using a CodeMirror-based editor.
1. Added the CodeMirror5 package
2. Added language and settings for "useAdvancedEditor"
3. Wrote AdvancedChatEditor.svelte
Thank you for your hard work on the project.
=> Add CodeMirror based Highlighted editor

src/lang/cn.ts, src/lang/de.ts, src/lang/en.ts, src/lang/ko.ts, src/lang/vi.ts, src/lib/Setting/Pages/LanguageSettings.svelte, src/ts/process/tts.ts, src/ts/storage/database.ts, src/ts/storage/globalApi.ts, src/ts/translator/translator.ts
1. DeepLX 를 번역 옵션에 넣고 URL, Token을 넣을 수 있게 하였습니다.
2. DeepLX 를 호출하는 로직을 넣었는데, DeepLX의 Body 중 Text는 완전한 텍스트로만 이루어져야 해서 번역 실행시 에러가 발생하는 중입니다. (DeepLX에 globalFetech로 호출은 정상적으로 가는중, body의 text타입만 해결하면 작동,)
3. TTS -> 일레븐랩스 호출시 body에 model을 다국어모델로 지정하였습니다. (정상작동)
4. globalFetch 함수를 리팩토링 하였습니다.
DeepLX 쪽만 해결방법을 찾으면 좋을 것 같은데 로직이 제가 생각한 것과 달라서 파악하는데 시간이 오래걸리고 있습니다.
DeepLX 부분 저도 더 로직 분석해볼 예정이지만, 
Body 부분에서 특수문자 제거 및 본문 텍스트만 파싱해서 번역 후 재조립하는 게 구현 가능하시다면 
해당 부분만 업데이트 해주시면 좋을 것 같습니다.
=> GlobalFetch 리팩토링, Elevenlabs 다국어모델 정보 body에 삽입, DeepLX 로직구현(미작동)

server/node/server.cjs
Fixed a bug caused by the "Content-Encoding" header returned from the server in some environments in the Risu environment of the NodeJS server.
In reality, the server does not return compressed data, but the issue arises from sending that header.
=> Fixed the 'failed to fetch', 'Decoding failed' errors occurring in some environments in NodeJS

src/lib/Playground/PlaygroundEmbedding.svelte, src/ts/process/memory/hypamemory.ts, src/ts/util.ts
Add support Openai-compatible custom embedding server on the playground.
Openai-compatible embedding servers:
https://github.com/toshsan/embedding-server
https://github.com/limcheekin/open-text-embeddings
https://github.com/michaelfeil/infinity
I only tested it with infinity. 
there is also a feature that If url does not end in /embeddings, automatically adds /embeddings.
I think I need to test it with more local embedding servers, but I think it'll be okay since it's only Playground
=> Add support for custom embedding URL in Playground

src/preload.ts
=> Fix typo in mainpage parameter name in preload.ts

src/ts/process/request.ts
it does not need models
due to me using nixos i cant really build it for my system. but i tested the web version and do not see why it would not work for other versions. furhtermore this is a backend issue so i doubt the ui changed anything
idk what that is. but i changed one line so i assume no
As described in #402 RisuAI would always try to reach localhost:11434 to connect to ollama. completely ignoring the user supplied adress. this fix addresses that. now it actually uses the correct url
=> Fixed ollama's hardcoded url

src/lang/ko.ts, src/ts/translator/translator.ts, src/ts/util.ts
I knew there was a `ParseMarkdown` function, but I didn't think it fit the current situation, so I created a new `applyMarkdownToNode` function, 
but I didn't see much difference in the results, So if you think `ParseMarkdown` is better, you can change my code to use that. 
(To use `ParseMarkdown`, we need to create a parameter that allows us to use `mconverted.parseInline` instead of `mconverted.parse` to the ParseMarkdown function)
=> Fix: Now combineTranslation applies the markdown to the result

src/ts/util.ts
Sorry but there were some markdown tags that I missed, But I think It's not an urgent patch like last time.
So If there are any tags I missed, I will continue commit to this pr until the next update.
=> Fix: handling more markdown in getNodetextToSentence

src/ts/process/request.ts, src/ts/tokenizer.ts
I fix the code which now make exception for gpt-based models so it can send logit_bias to server and gpt4o with reverse_proxy automatically choose new tokenizer.
=> Make logit_bias work for all gpt-based multimodal models & Add supports of gpt-4o tokenizer for reverse_proxy

src/lib/Setting/Pages/BotSettings.svelte
Apart from pr, I wish reverse proxy had showUnrec too like the official openai setting
=> Add GPT-4o in Custom (OpenAI-compatible)

src/ts/parser.ts
- [v] Did you check if it works normally in all models? *ignore this when it dosen't uses models*
- [v] Did you added a type def?
Add a curly syntax for retrieving the index for the selected alternate first message. {{first_msg_index}} replaced with -1 if the default first message is being used, otherwise it's replace with the selected index of alternate first message.
=> feat: Add first_msg_index curly syntax

src/ts/parser.ts
- [v] Did you check if it works normally in all models? *ignore this when it dosen't uses models*
- [v] Did you added a type def?
Remove unnecessary check when substituting first_msg_index that is preventing it to be used within non-chat context (e.g. lorebook)
=> feat: Substitute first_msg_index even if context is not chat

src/lang/cn.ts, src/lang/en.ts, src/lang/ko.ts, src/lang/zh-Hant.ts, src/lib/Setting/Pages/LanguageSettings.svelte, src/ts/storage/database.ts, src/ts/translator/translator.ts
1. LLM 번역 응답 크기 소프트코딩화
2. LLM도 DOM파서를 통한 문장 단위 및 병렬 번역을 하도록 수정
3. 바깥쪽 태그가 제대로 제거가 안되는 문제 해결
4. 추가적으로, 기본 번역 프롬프트를 ```You are a translator. Translate the following html or text into {{slot}}. Do not output anything other than the translation, punctuations and quotation marks.```으로 변경하고 싶습니다.
------
1. Softcoded LLM translation response size
2. Modified LLM to also do sentence-by-sentence and parallel translation via DOM parser
3. Fixed an issue with outer tags not being removed properly
4. Additionally, I want to change the default translation prompt to ```You are a translator. Translate the following html or text into {{slot}}. Do not output anything other than the translation, punctuations and quotation marks.```
=> Improve LLM Translation

server/node/server.cjs, src/ts/storage/nodeStorage.ts
노드리스의 /api/write와 /api/read에서 base64를 제거해 파일 용량 과 I/O에 필요한 연산량을 줄였습니다.
Removed base64 from /api/write and /api/read on node version rise to reduce file size and the amount of computation required for I/O.
=> Enhance Node Version RisuAI Backend Server File I/O Performance

src/lib/Setting/Pages/BotSettings.svelte, src/ts/process/request.ts
Add sonnet 3.5 for aws and custom, also added gpt-4-turbo from custom.
=> add sonnet 3.5 for aws and custom

src/ts/process/triggers.ts
=> Fix: now simpleLLM requires low level access

src-tauri/Cargo.toml, src-tauri/src/main.rs, src/ts/storage/globalApi.ts, src/ts/storage/risuSave.ts
It's a known issue that IPC call in Tauri V1 is slow (https://github.com/tauri-apps/tauri/issues/4197) Specifically, writeBinaryFile can take several seconds if the file is around like 10 MB because of some internal serealization bottleneck of Tauri. This is really bad as we use writebinaryFile every second to save database. 
This PR just create separate http server only handling the bottleneck part: writebinaryfile of database.bin and assets.
=> Optimize tauri write binary file

server.bat, server.sh
When running `npm install` followed by `npm run build` in the Node version, the build process fails with multiple errors indicating that various Svelte components and stores are not defined.
- Updated `server.bat` to use `pnpm install`, `pnpm run build`, and `pnpm run runserver`.
- Updated `server.sh` to use `pnpm install`, `pnpm run build`, and `pnpm run runserver`.
---
The errors encountered when using `npm install` in the Node version include:
- 'loadedStore' is not defined
- 'WelcomeRisu' is not defined
- 'settingsOpen' is not defined
- 'Settings' is not defined
- 'GridChars' is not defined
- 'DynamicGUI' is not defined
- 'Sidebar' is not defined
- 'sideBarStore' is not defined
- 'ChatScreen' is not defined
- 'alertStore' is not defined
- 'AlertComp' is not defined
- …
=> Fix build errors in Node version by updating scripts to use pnpm instead of npm

src/ts/process/triggers.ts
Currently, some of the operators in the trigger block seem to be working in reverse.
=> Fix trigger operator

src/ts/process/scripts.ts
Asset list can be different depending on character. Technically, we should also invalidate cache when asset list is changed but I doubt people will hit this case often. (bot maker somewhat hit it though so maybe worth taking care of)
=> fix: finer granularity cache key for dynamic assets

src/ts/mutex.ts, src/ts/process/lua.ts
First commit fixes this 
runLua function gets run in two different paths (i.e. runLua for lua edit triggers and another one for onOuput handling) However, when one of invocations waits for another promise from js side (i.e. low level function) to finish, it gives chance for next trigger mode to run which would call `if(luaEngine){ luaEngine.global.close() }` that will close lua engine for the invocation that was waiting for promise which is problematic. 
Second commit fixes this by having a pool of engine for each trigger mode having single mutex that prevents running same engine at the same time while allowing different tigger modes to run parallely
This was causing insane lagging and buggy behaviours. Third commit fixes this.
=> Fix various lua low level access bugs

src/ts/process/request.ts
I think db.advancedBotSettings is code that should have been deleted, but was not accidentally removed.
=> Remove db.advancedBotSettings in request.ts

src/lib/SideBars/Scripts/TriggerList.svelte
I propose this change to address the issue of the page freezing in the current trigger lua editing screen.
=> Fix Sortable initialization error

src/ts/process/lua.ts, src/ts/process/triggers.ts
This pull request resolves the issue where the chat object used in the Lua engine was fixed at the time of initialization. This also addresses issue #563.
=> fix: chat sync issue in lua engine

package.json
> [!NOTE]
> This checkbox is intentionally left unchecked due to an ongoing issue https://github.com/kwaroran/RisuAI/issues/641. If this issue is related to the pnpm version, this PR should not be merged.
This PR specifies the exact version of pnpm to be used for this project by adding the `packageManager` field to the `package.json` file.
- Specified `"packageManager": "pnpm@9.10.0"` in `package.json`
By explicitly declaring the pnpm version in `package.json`, we ensure consistent package management across different development environments. This addresses compatibility issues between the project's lockfile and pnpm versions, preventing potential problems that could arise from version mismatches.
The pnpm version 9.10.0 used in this PR is based on my current development environment. This …
=> chore: Specify pnpm version

src/ts/storage/globalApi.ts, src/ts/util.ts
This PR is not an ideal solution, but it provides a workaround for the issue where a specific built-in function of Tauri causes freezing in non-Tauri environments like Fixes #641.
=> fix: conditionally initializing getCurrentWebviewWindow

src/lib/ChatScreens/Chat.svelte
- [v] Did you added a type def?
This pull request adds `{{role}}` support to the recently introduced Custom HTML feature. Although documentation indicated that CBS was supported in Custom HTML, the `{{role}}` CBS was returning `null` instead of rendering the intended values.
By passing `getCbsCondition()` as the second argument to `risuChatParser`, `{{role}}` now renders as expected in Custom HTML, allowing users to apply conditional logic based on roles.
If there is an alternative way to enable `{{role}}` support in Custom HTML without this modification, feel free to close this PR. Thanks for checking it out!
=> Fix {{role}} CBS support to custom HTML

src/ts/process/request.ts
- [No] Did you check if it works normally in all models? *ignore this when it dosen't uses models*
This only takes effect on AWS Claude models
- [Yes] Did you check if it works normally in all of web, local and node hosted versions? if it dosen't, did you blocked it in those versions?
- [No] Did you added a type def?
AWS Claude model calling no longer supports direct calling, but supports Cross-region inference instead. All Cross-region inference model profile IDs equal to original model name with "us." in the beginning. Reference: https://us-east-1.console.aws.amazon.com/bedrock/home?region=us-east-1#/inference-profiles
=> Fix AWS Claude Support

src/lib/ChatScreens/Chat.svelte
This PR updates the `renderChilds` function to properly handle `TextNode` rendering. Previously, `renderChilds` only iterated over `children`, which excluded `TextNode`s and rendered only `HTMLElement`s. Now, the function iterates over `childNodes`, ensuring that:
1. **TextNodes**: Are rendered by displaying their `textContent`.
2. **ElementNodes**: Are rendered as before, using `renderGuiHtmlPart`.
Initially, I wondered whether the absence of `TextNode` rendering might have been due to security considerations. However, since elements like headings (`h1`), lists (`ul`, `li`), and strong text (`strong`) were already being rendered, it seems likely that the exclusion of `TextNode` rendering was an oversight rather than an intentional decision.
I believe that these elements are meaningful …
=> Add text node rendering to custom HTML

src/ts/parser.svelte.ts
This PR resolves an issue where assets were not visible on macOS when using `asset://localhost/` URLs.
The problem occurred because **DOMPurify** was removing the `src` attribute when its value started with `asset://localhost/`. This behavior affected the visibility of assets on macOS for the Local version of RisuAI.
To address this, I chose to use `DOMPurify.addHook` to allow `src` attributes starting with `asset://localhost/` for certain tags.
I also thought about another solution: passing `ALLOWED_URI_REGEXP` to `DOMPurify.sanitize`. However, I decided not to use it because it would require using regular expressions to check strings every time the method is called, which might be less efficient in my opinion.
While this issue is specific to macOS and the Local version of RisuAI, I …
=> Fix macOS Asset Visibility Issue in Local Version of RisuAI

src/lib/Setting/Pages/BotSettings.svelte
Current build doesn't have aws key slot.
Thank for your time.
=> Fix missing aws key slot

src/lang/en.ts, src/lib/ChatScreens/Chat.svelte, src/lib/Setting/Pages/LanguageSettings.svelte, src/ts/storage/database.svelte.ts, src/ts/translator/translator.ts
Please introduce an autoTranslateCachedOnly option that automatically translates only previously translated text when enabled.
- LLM-based translations can be relatively costly, so end users may not want new/specific text to be automatically translated.
- End users may prefer not to manually click the translate button when viewing chat logs that have already been translated.
- By utilizing cached translations more effectively, we can enhance the overall user experience.
=> Add autoTranslateCachedOnly option for LLM-based Translation

src/lib/ChatScreens/Chat.svelte
This PR introduces a fix for an issue where cache misses occur when translateBeforeHTMLFormatting is disabled. Previously, the 'Auto Translate Cached Only' feature only worked when translateBeforeHTMLFormatting was enabled. This update ensures that cached translations are used properly even when translateBeforeHTMLFormatting is disabled.
Thank you for taking the time. This is not an urgent matter, but I would appreciate it if you could incorporate this PR along with other changes in the next update.
=> Fix cache handling for autoTranslateCachedOnly when translateBeforeHTMLFormatting is disabled

src/ts/translator/translator.ts
This PR introduces a fix for the issue where the input auto-translation field ("Enter Message for Translate to English" text displayed when nothing is entered) was not correctly translating the original text into English in the LLM-based translation.
Additionally, this update ensures that "Curly Braced Syntaxes {{slot}}" are translated into the user's native language when the translation button is pressed, and into English during the input translation, facilitating more effective translation.
=> Fix translation issue in input auto-translation field for LLM-based Translation

src/ts/parser.svelte.ts
This PR fixes an issue where indentation and whitespace inside the {{#if_pure}} syntax were being trimmed.
I made an effort to minimize the impact on the parser's existing behavior.
=> Fix {{#if_pure}} syntax issue where indentation and whitespace were not preserved as intended.

src/ts/process/memory/hypav2.ts
This PR fixes hypav2 issue where the "search_document: " string is not truncated correctly.
If the "search_document: " string is not truncated correctly, it will cause "t: " to remain within the <Past Events Details></Past Events Details> tag.
Edit: This PR also add memo "supaPrompt" to detect supaMemory model requests in the plugin
=> Fix hypav2 issue where the 'search_document: ' string is not truncated correctly.

src/lib/ChatScreens/Chat.svelte
There was an issue where the autoTranslateCachedOnly option was being ignored when sending messages. This occurred due to the way the translated variable was initialized with let translated = $state(DBState.db.autoTranslate).
=> Fix issue with autoTranslateCachedOnly option being ignored when sending messages

src/ts/process/request.ts
- [YES, I tested it on models from OpenAI/Anthropic/Google.] Did you check if it works normally in all models? *ignore this when it dosen't uses models*
- [No, I've only tested it on node hosted versions] Did you check if it works normally in all of web, local and node hosted versions? if it dosen't, did you blocked it in those versions?
- [No] Did you added a type def?
Fixed an issue where the “Temperature” parameter was not scaled correctly when using the “Separate Parameters” feature.
=> Fixed “Separate Parameters” scaling issue

src/ts/process/index.svelte.ts
This PR updates the regex used for extracting <Thoughts> content to handle multiline cases reliably. The previous regex (.+?) had limitations when processing text spanning multiple lines, as it could not match content with line breaks.
=> Fix thoughts extraction regex for multiline content handling

src/ts/plugins/plugins.ts
- It doesn't use models.
- Only checked on the browser
- It does nothing with types
In plugins.ts methods `addRisuReplacer` and `removeRisuReplacer` are implemented but not defined (exported).
I thought that the definitions were simply missing. So I added only two lines.
=> fix: add missing definitions of plugin APIs

src/ts/plugins/plugins.ts
In plugins.ts methods `addRisuScriptHandler` and `removeRisuScriptHandler` are implemented but not defined (exported).
Thanks for your time.
=> fix: add missing api definition

plugins.md
It's just a docs change.
Fixed example code in the plugin docs to match with Plugin Syntax.
=> Fixed example code error in plugin docs

src/ts/process/tts.ts
This pull request resolves a `TypeError` that occurred specifically when executing TTS with the `gptsovits` model.
In Edge browsers, this manifested as:
`TTS Error: TypeError: Cannot read properties of undefined (reading 'model')`
While the TTS functionality itself was working, a missing `break` statement in the `gptsovits` case of the `sayTTS` function caused this error during runtime. This PR adds the necessary `break` statement to prevent this `TypeError`.
=> Fix TTS TypeError issue when using gptsovits TTS by adding missing break statement

src/ts/drive/backuplocal.ts
Previously, the backup loading was depending on ArrayBuffer. In chromium based browsers, ArrayBuffer's size is limited to 2GB, and anything more will fail to read the data.
This affects Tauri too, as Tauri uses Edge webview2 which also is based on chromium.
The proposed change uses file stream instead of ArrayBuffer, effectively ignoring forced file size limit of 2GB.
Have to revise, if possible. But really didn't changed that much logic and since it is only a typescript file change, it will work on most cases.
Worked on node hosted chrome environment with 2.25GB of binary backup file.
=> fix: backup size limit

package.json, pnpm-lock.yaml, src/lib/Setting/botpreset.svelte
This PR adds a **prompt comparison feature** to the prompt preset interface. Now, users can compare two different prompts to identify differences.
1. Open the prompt preset window.
2. Click the diff button (next to the copy button) for the first prompt to use as the baseline. The button will turn green, indicating selection.
3. Click the diff button for the second prompt to compare against the baseline. A diff view will appear.
4. Clicking the same diff button twice will clear the selection.
- Line-level comparison
- Modified lines: blue vertical line.
- Deleted content: red text on red background with red vertical line.
- Added content: green text on light green background with green vertical line.
- If the prompt content is identical, the following message will be displayed at the top …
=> feat: add prompt comparison feature

src/ts/process/request.ts
fix gemini multimodal error.
ERROR MESSAGE : Invalid value at 'contents[6].parts[1]' (oneof), oneof field 'data' is already set. Cannot set 'text'
=> fix: gemini multimodal

src/lang/en.ts, src/lib/Others/AlertComp.svelte, src/lib/Setting/Pages/OtherBotSettings.svelte, src/lib/SideBars/CharConfig.svelte, src/ts/alert.ts, src/ts/process/index.svelte.ts, src/ts/process/memory/hypamemory.ts, src/ts/process/memory/hypav3.ts, src/ts/storage/database.svelte.ts
Implemented HypaV3, a variation of the HypaV2 memory.
---
Key Changes:
- Ratio-based token management instead of fixed token counts (memoryTokensRatio, extraSummarizationRatio)
- Improved memory selection with adjustable ratios (recent/similar/random memory)
- Similar memory selection now uses parent summaries instead of individual chunks
- Selected memories are chronologically ordered
- Control over summary units (maxChatsPerSummary)
- Added orphaned memory preservation option (preserveOrphanedMemory)
---
New Settings:
- memoryTokensRatio: Ratio of memory prompt in max context size
- extraSummarizationRatio: Extra margin ratio of max context size to keep more free space when summarizing begins
- maxChatsPerSummary: Maximum chats per summary
- similarMemoryRatio: Ratio for …
=> feat: Implement HypaV3 ratio-based memory (Variation of HypaV2)

src/lib/Setting/botpreset.svelte
This PR introduces a couple of usability improvements to the prompt comparison functionality.
1. If the two prompts are identical
Instead of showing the content right away, an alert is displayed saying the two prompts are the same. Only when the user clicks "Yes" the content will be shown. This avoids unnecessary confirmation of identical prompts.
2. If the two prompts are different
A summary of the number of modified, added, and removed lines is displayed.
When hovering over the summary, a quick overview of the changes appears. When only a single word or character is modified, it was previously hard to identify the line that was changed. Now, the overview improves clarity, making it easier to understand the changes.
On mobile devices (tested on iOS 16.7), tapping on the 'Differences …
=> Improve prompt comparison functionality with usability enhancements

src/ts/process/index.svelte.ts
This PR addresses an issue where the `{{chat_index}}` cbs does not work correctly in regex scripts of the 'Modify Request Data' (editprocess) type. To work around this issue, I propose changing the function used in this section to `processScriptFull()`.
If you have any other suggestions, such as modifying the arguments instead, please feel free to let me know.
Thanks for your time and consideration.
=> suggestion: apply 'processScriptFull()' to 'editprocess' mode regex script

src/ts/process/index.svelte.ts
This PR ensures that the 'position' lorebook decorator is correctly applied to alternate (replaced) GlobalNotes.
Thank you for your time and consideration.
=> feat: apply positionParser to alternate global note

src/lib/Setting/botpreset.svelte
This PR adds a small improvement to the prompt comparison functionality.
When the two prompts are different, the tooltip overview now enables clicking on modified parts to navigate directly to the corresponding lines.
Previously, finding the modified parts required manual scrolling. With this update, it becomes much easier to locate and review the changes, even for very long prompts.
When navigating to a modified part, the target line is highlighted in yellow for 1 second to indicate the clicked location.
https://github.com/user-attachments/assets/577973cc-18d0-4e73-814e-7ba01bb9950c
For mobile devices, this functionality has been tested on iOS 16.7.
If there are any suggestions for improvement or concerns about the implementation, feedback is greatly appreciated. It’s completely …
=> feat: add navigation to modified lines in prompt comparison

src/lib/Others/AlertComp.svelte, src/lib/Others/HypaV3Modal.svelte, src/lib/Setting/Pages/OtherBotSettings.svelte, src/lib/SideBars/CharConfig.svelte, src/ts/process/memory/hypav3.ts
- feat: add translate button to HypaV3 modal
- feat: add dual-action translation (cached/regenerate) in HypaV3 modal
- Implements shift+click (desktop) and double tap (mobile) for regenerating translations while maintaining regular click/tap for cached translations.
- feat: improve ratio sliders interaction in HypaV3 settings
- feat: add lastSelectedSummaries property to store selected memory indices
- feat: display next message to be summarized in HypaV3 modal
=> feat: improve HypaV3

src/ts/plugins/plugins.ts
It would be nice if plugins could change their settings directly in the db.
This PR introduces an API that makes this simple.
=> feat: add setArg to plugin v2

src/lib/Others/HypaV3Modal.svelte
This PR introduces fix: ensure scrollToSelection works cross-browser in HypaV3 modal
=> fix: ensure scrollToSelection works cross-browser in HypaV3 modal

src/lib/Others/HypaV3Modal.svelte
This PR introduces fix: resolve mobile keyboard enter button not working in HypaV3 modal
=> fix: resolve mobile keyboard enter button not working in HypaV3 modal

src/ts/observer.ts, src/ts/process/lua.ts
This pull request reintroduces charJS style button event previously deprecated and removed, using luaEngine. This implementation diverges from current style by passing attribute data as parameters rather than function names.
=> feat: charjs style button trigger

src/lib/Setting/Pages/Module/ModuleSettings.svelte
This PR fixes an issue where a removed module remains active until the app is restarted if it was enabled at the time of deletion.
=> fix: disable module before remove

src/ts/parser.svelte.ts
This PR contains modifications to import only the required assets when talking to Asset Bot.
- refactor parseAdditionalAssets()
- Modified the getClostMatch() to work well with Object<key, value> to which it is dynamically added.
=> refactor(parser): import only the required asset when in a node environment

public/sw.js
Currently, a specific endpoint that calls /sw/check in the service worker checks whether '/sw/check' is cached.
Since the service worker does not have any logic to cache /sw/check itself, the service worker will always respond that there is no cached data.
This forces all data to be re-registered when getFileSrc is called from globalApi.svelte.ts, and bots with a lot of assets will re-register all data, which slows down bot changes.
Since I am not familiar with the internal structure of RisuAI, I have temporarily modified the code to check /sw/img when the service worker checks /sw/check.
=> Fix: Replace /sw/check to /sw/img in service worker checkCache

src/ts/process/memory/hypamemory.ts
The error messages were not properly displayed, showing [object Object] instead of the actual content.
<br>
This PR improves error handling to display actual error content.
=> fix: stringify object in HypaProcesser to display actual error content instead of [object Object]

src/lib/SideBars/LoreBook/LoreBookSetting.svelte
- Add buttons to toggle all character/chat lorebooks' always-active state at once
- Show SunIcon when all lorebooks are active, LinkIcon otherwise
=> feat: add global toggle buttons for lorebook always-active state

src/ts/parser.svelte.ts, src/ts/process/modules.ts
This PR addresses the issue where asset names were only recognized when entered in lowercase, even if they were originally uppercase. It ensures that asset names are now case-insensitive, aligning with the intended behavior.
=> fix: issue with asset names case-insensitive

src/lib/Setting/Pages/Module/ModuleSettings.svelte, src/ts/process/modules.ts
It seems modifying an already activated module is causing a synchronization issue with the current chats. Correcting this should fix it.
=> fix: force refresh modules after closing menu

src/lib/SideBars/SideChatList.svelte, src/ts/characters.ts, src/ts/storage/database.svelte.ts, src/ts/util.ts
이 PR은 챗을 분류하는 폴더를 추가합니다. 폴더에는 색상을 넣을 수 있습니다.
This PR adds a folder to categorize chats. Folders can be colored. I'm open to any feedback or suggestions.
=> feat: Chat Folder

src/ts/observer.svelte.ts, src/ts/process/lua.ts, src/ts/process/triggers.ts
The community have reported an issue where chat array-related effects malfunction when using modules using Lua alongside modules using blocks. It appears that my previous PR, #639, may be the cause of this problem. This PR included the following changes:
1.  Reverted a previous change to allow Lua triggers to cycle correctly within the trigger pipeline.
2.  After that, the issue that the previous PR attempted to fix has (understandably) resurfaced. To address this, I've taken a different approach: To prevent a situation where a created Lua mutex would eternally reference a single chat object if not initialized again, I've added a chat variable to the `luaEngineState` interface and updated it on every call.
3.  I noticed that the `removeChat` function was included twice in the Lua …
=> fix: lua chat functions

src/lib/ChatScreens/DefaultChatScreen.svelte
Because of this, even when useAutoTranslateInput is turned off, Google translation request runs every time a sentence is modified.
=> Fix: translation request was made even though useAutoTranslateInput is turned off

src/ts/process/index.svelte.ts, src/ts/process/lua.ts
This PR aims to fix the following issues:
1.  Fixed an issue where chat array changes caused by the 'start' mode trigger were not being applied correctly. (This problem occurs in both block type and Lua type.)
2.  Occasionally, there was a problem with scriptstate desync in Lua triggers, so I've changed to update method on every call.
=> fix: Chat trigger on start

plugins.md, src/ts/plugins/plugins.ts, src/ts/process/request.ts
- Add setArg function to plugin docs
- Add abortSignal parameter to addProvider function
=> fix: update plugin docs with abortSignal support

src/ts/process/memory/hypamemory.ts
- Add custom embedding model name as suffix to hypaVector storage keys when using custom embedding models to prevent vector dimension mismatch errors.
=> fix: add custom embedding model name as suffix to hypaVector storage keys

src/ts/process/infunctions.ts
It has been reported that calcString incorrectly calculates expressions when a negative number appears on the right-hand side. This pull request addresses this issue.
=> fix: treating unary minus in calcString

src/lib/Setting/Pages/Module/ModuleSettings.svelte, src/ts/parser.svelte.ts
It appears that the `previous_chat_log` cbs currently behaves differently than described in the documentation.
Thank you for your time.
=> fix: 'previous_chat_log' cbs

package.json, pnpm-lock.yaml, server/node/server.cjs, src/ts/characterCards.ts
- [❌] Have you checked if it works normally in all models? *Ignore this if it doesn't use models.*
- Not applicable
- [✅] Have you checked if it works normally in all web, local, and node hosted versions? If it doesn't, have you blocked it in those versions?
- Done
- [❌] Have you added type definitions?
- Not applicable
The Node.js hosted version of RisuAI encountered an issue where it failed to fetch data from the Risu Realm server when accessed remotely.
RisuAI's frontend directly fetches data from the Realm server (e.g., sv.risuai.xyz). While the official web version did not exhibit CORS errors (potentially due to same-origin deployment or specific server-side CORS configurations), running the Node.js version on a self-hosted server and accessing it remotely resulted in browser CORS …
=> Fix: Resolve Realm CORS Violation for Node.js Hosted Version

src/ts/process/memory/hypav3.ts
- fix: check empty summarization result in HypaV3
- fix: handle similarity search error in HypaV3
=> fix: improve error handling in HypaV3

src/ts/process/lua.ts
This PR addresses an issue where `luaFactory` fails to initialize correctly in 'editDisplay' mode under specific conditions.
The initialization failure can be reliably reproduced under the following conditions:
1. Disable all modules.
2. Select any chatbot with 'editDisplay' in trigger lua.
3. Select or make chat with length of 2 or more.
4. Restart app and revisit the chatbot
1.  Guaranteed `luaFactory` initialization completes successfully during concurrent calls.
2.  Added `Promise Map` to ensure only one Lua engine instance is created per mode, preventing redundant initializations.
3.  Moved variable updates within mutex scope to prevent potential issues during concurrent operations.
4.  Resolved merge conflicts with another PR. During the resolution:
*   Removed logic related to …
=> fix: Lua factory init failure under concurrent display editing

src/ts/process/scripts.ts
This PR aims to:
1.  Fix an issue where the current regex caching is incompatible with modules.
2.  Slightly modify the hashing structure to handle non-deterministic regex with cbs. Verified that this correctly handles expressions like `{{#if A}}`.
Thanks for your time.
=> refactor: regex caching

src/ts/process/lorebook.svelte.ts
This PR aims to address the following issues:
*   Fixed problems where prefixes and suffixes in the Lorebook prompt were affecting keyword matching logic.
1.  In full word matching, the first and last words of the body text would consistently fail to match.
2.  In general matching, using a persona name as a keyword would always result in a match, regardless of context.
*   I tried to preserve the original code structure as much as possible while implementing these fixes. Please feel free to suggest changes to the approach if you see a better way.
Thank you for your time and review.
=> Fix: Issue with Lorebook prompt prefix/suffix affecting matching

src/lib/Setting/Pages/PersonaSettings.svelte
This PR introduces the persona sorting feature.
**Changes:**
1.  Uses the `sortable` library, consistent with other sorting functionalities.
2.  To prevent desynchronization between the selected persona and the UI value during sorting:
*   `OnStart`: Saves the currently selected persona.
*   `OnEnd`: Switches selection to the first persona without saving the initial selection.
I believe I've tested this sufficiently, but please feel free to point out any potential issues or edge cases I might have missed.
Thank you for your time and review!
=> feat: add persona sort

src/ts/process/stableDiff.ts
In some ComfyUI workflows, output.images is often undefined when intermediate outputs from text-based nodes are included and cannot be suppressed in the response.
=> Fix: Avoid flatMap crash when output.images is undefined

src/ts/process/lua.ts
This PR aims to make the alertSelect trigger usable in Lua as well.
Here is the Lua code used for testing:
```Lua
testSelect = async(function(id)
-- declare string table
local strTable = {
"test1",
"test2",
"test3",
"test4",
"test5",
}
local testVar = alertSelect(id, strTable):await()
print('testVar')
print(testVar)
end)
```
=> feat: alertSelect for triggerlua

src/lib/ChatScreens/DefaultChatScreen.svelte
Prevented lazy loading of blocks when no chat is selected.
=> fix: prevent blocks lazy loading when no chat selected

src/ts/process/lorebook.svelte.ts
Filled data field when creating a recursive lorebook.
=> fix: prevent missing data field for recursive lorebook

src/lang/en.ts, src/lang/ko.ts, src/lib/Others/AlertComp.svelte, src/lib/Setting/Pages/AdvancedSettings.svelte, src/ts/process/index.svelte.ts, src/ts/storage/database.svelte.ts
This PR adds an optional feature to store prompt preset metadata in each chat message.
---
When writing prompts, it's common to test **dozens of prompt presets** across many messages. After just a day or two, it's hard to remember which message used which prompt.
This is especially important for sensitive models, where even small changes to prompt wording or toggle combinations can greatly affect output.
---
To support this, an option has been added to **Advanced Settings** that stores:
- Prompt preset name (*Add Prompt Info to Chat*)
- Active custom toggles (*Add Prompt Info to Chat*)
- Prompt text (*Add Prompt *Text* To Chat*):
Only the **Prompt Template** portion of the final prompt (**as sent**) is stored — character description, persona, lorebook, and long-term memory are excluded to …
=> feat: add optional prompt metadata saving to chat messages

src/lib/Setting/Pages/OtherBotSettings.svelte, src/ts/storage/database.svelte.ts
Removed duplicated nai settings inputs for `noise_schedule` and `cfg_rescale`.
=> fix: remove dupilacted nai settings input

src/ts/process/lua.ts
The `getDescription(triggerId)` function, documented at: https://kwaroran.github.io/docs/srp/lua/#getdescriptiontriggerid was missing from the codebase and has now been added.
- [  ] Have you checked if it works normally in all models? *Ignore this if it doesn't use models.*
- [ o] Have you checked if it works normally in all web, local, and node hosted versions? If it doesn't, have you blocked it in those versions?
- [  ] Have you added type definitions?
=> Add getDescription function to LUA script (was missing)

src/lib/ChatScreens/DefaultChatScreen.svelte
This PR resolves an issue appeared in [Revert to old loading temp](https://github.com/kwaroran/RisuAI/commit/858d6c2ad229076f7cbe85158a7077e51ea41d06)
=> fix: resolve Hypa V3 button disappearing from menu

src/ts/alert.ts
It fixes a bug identified during the testing of ComfyUI image generation in Playground. Specifically, the error alert, which is supposed to display error messages, was not appearing when a parameter was of an error type. This fix ensures that error alerts are now correctly displayed under such conditions.
=> fix: error alert not showing when parameter is error type

src/ts/globalApi.svelte.ts
While tracking down the error "The first argument must be one of type string, Buffer, ArrayBuffer, Array, or Array-like Object. Received type undefined" that occurs during ComfyUI image generation, I found an issue in the `fetchNative` function.
When sending GET or DELETE requests, the `realBody` variable is set to `undefined`, but it's directly passed to `Buffer.from()` without null checking, causing the error.
Added a simple null check to prevent the error:
```typescript
// Before
body: Buffer.from(realBody).toString('base64'),
// After
body: realBody ? Buffer.from(realBody).toString('base64') : '',
=> fix: prevent `Buffer.from(undefined)` error in native fetch for GET/DELETE requests

src/lib/SideBars/Toggles.svelte, src/ts/util.ts
| Before | After |
| --- | --- |
|![image](https://github.com/user-attachments/assets/9d6281fe-3be6-4b51-8ca1-dab20c666945) | ![image](https://github.com/user-attachments/assets/3cec282c-29ed-4a9e-af03-9ee1f1ed4fab)|
Instead of pseudo-dividers with unwanted checkboxes, this allows creators to define a "divider" *toggle*.
Dividers are created by keyless `=name=divider`, or keyless valueless `==divider`.
```
=My Module=divider
==divider
```
Multiple dividers with equal label will merge into one to prevent too many dividers from multiple modules covering everything up.
```
// these won't merge
==divider
=K=divider
// these will merge
==divider
==divider
```
Groups are opened by keyless `=name=group` and closed by keyless valueless `==groupEnd`. Nesting is not supported.
| Opened groups | …
=> feat: Add 'divider' and 'group'/'groupEnd' type toggle

src/lib/SideBars/Scripts/TriggerList2.svelte
Standardize variable name display color to yellow
=> Fix: variable name color inconsistency

src/lib/Others/AlertComp.svelte
I can't find the history but `onclick` is always `undefined`, never assigned. But it's being called in an `onclick`. This blocks all types of exports. I just removed it.
=> fix: Undefined property access in AlertComp

src/lib/SideBars/Toggles.svelte
When dividers within a group becomes many, it would throw.
Found out that the divider was referencing the whole list of toggles (root level), not `items` (items of a group it belongs), as divider development happened before the group. It caused out of index array access and `prevToggle.type` would throw because `prevToggle` can be `undefined`.
=> fix: Divider toggles should reference within group

src/lib/SideBars/Scripts/TriggerList2.svelte
This PR addresses an issue where the indentation for the Trigger V2 effect description was only applied to the first line.
To improve code readability, the indentation has now been applied consistently to all lines of the effect description.
This was achieved by changing the surrounding element from a `<span>` to a `<div>`, removing the inline structure that prevented multi-line indentation.
=> Fix: Apply indentation to all lines for Trigger V2 effect description

src/lib/SideBars/Scripts/TriggerList2.svelte
When saving nested if/else blocks, v2EndIndent was incorrectly being added after v2Else when addElse was enabled. This PR corrects the positioning so that v2EndIndent is properly generated before v2Else instead of after it.
=> Fix: v2EndIndent positioning in nested if/else statements in Trigger v2

src/ts/globalApi.svelte.ts
This PR fixes an indexing bug in the response streaming logic under the Tauri environment.
Previously, `addFetchLog` returned `fetchLog.length - 1`, but because new logs are added to the front of `fetchLog` with `unshift`, the latest log is always at index `0`. As a result, `pipeFetchLog` was updating the wrong log entry during streaming, since it uses `fetchLog[fetchLogIndex].response += chunk` to update the log.
Now, `addFetchLog` always returns `0`, so `pipeFetchLog` updates the correct log entry for streaming responses.
```ts
// Inside fetchNative()
let fetchLogIndex = addFetchLog({ ... });
let readableStream = pipeFetchLog(fetchLogIndex, ...);
// Inside pipeFetchLog()
fetchLog[fetchLogIndex].response += chunk; // <- must point to the latest log
```
---
**Note:**
In …
=> Fix: fetchLog index bug in response streaming (Tauri)

src/lib/Setting/Pages/DisplaySettings.svelte
Corrected span class notation: single and double quotes were swapped.
=> Fix: swapped span classes for single and double quotes

src/lib/Others/GridCatalog.svelte
This PR introduces a back button to the GridCatalog screen. This allows users to easily navigate back to the previous view.
=> Feature: Add back button to GridCatalog

src/ts/process/scriptings.ts
Lua API functions `getCharacterLastMessage` and `getUserLastMessage` are much needed functions for retrieving the most recent character and user messages.
The use of such functions will simplify the Lua code significantly by eliminating the need to search through the code. Take a look at the following example:
```
function getCharacterLastMessage(id)
local fullChat = getFullChat(id)
for i = #fullChat, 1, -1 do
local message = fullChat[i]
if message.role == "char" then
return message.content
end
end
return nil
end
local lastcharmessage = function getCharacterLastMessage(triggerId)
```
With the new function, the code does not need to declare a new function:
```
local lastcharmessage = function getCharacterLastMessage(triggerId)
```
function `getCharacterLastMessage()` will return the first …
=> New Lua functions for retrieving last character and user messages

src/ts/process/scriptings.ts, src/ts/util.ts
Normally this shouldn't happen, but I found an issue in triggerLua where adding a chat with null data via the `addChat` API would make that chat inaccessible. This PR prevents that from happening and makes already broken chats accessible.
=> fix: add null check for addChat in scripting API

src/lib/Setting/Pages/AdvancedSettings.svelte
Added delete and reorder features to the Custom Model accordion component. Also implemented saving and reflecting the expansion state (open/closed) for each item.
=> Feature: Add delete and reorder functionality to Custom Model accordion

src/lib/Setting/botpreset.svelte
This PR adds the ability to reorder prompt presets using a drag-and-drop interface.
=> Feature: Add drag-and-drop reordering for prompt presets

src/lib/ChatScreens/Chat.svelte, src/lib/Setting/Pages/Module/ModuleChatMenu.svelte, src/ts/stores.svelte.ts
Made sure that changes to `$ReloadGUIPointer` really, really update the heavy part. Also, changing per-chat module activation will result in `$ReloadGUIPointer` increase as well.
Confirmed reloading with the new chat list implementation.
=> fix: Make sure to update whole chat when necessary

src/ts/process/mcp/risuaccess.ts
This PR corrects the sorting order of the getChatHistory tool. It was returning messages oldest-first, which contradicted its schema description (ordered by time, newest first).
=> Fix getChatHistory in risuaccess MCP

src/ts/process/request/google.ts
Moved the body.tools removal out of the GoogleCloud.VertexAIGemini if statement so it will also be applied for newer models that use the LLMFormat.GoogleCloud
This fixes an issue when calling the GoogleAI directly without any tools loaded it will produce the error:
```
{
"error": {
"code": 400,
"message": "The GenerateContentRequest proto is invalid:\n * tools[0].tool_type: required one_of 'tool_type' must have one initialized field",
"status": "INVALID_ARGUMENT"
}
}
```
This is identified as a bug in: https://discord.com/channels/1108412316619391006/1382932637072752680
I was able to reproduce and fix the error with this very minor change.
=> Moved the body.tool removal to fix GoggleAI error.

src/lib/Others/HypaV3Modal.svelte, src/lib/Others/HypaV3Modal/modal-header.svelte, src/lib/Others/HypaV3Modal/types.ts, src/lib/Others/HypaV3Modal/utils.ts, src/ts/process/memory/hypamemoryv2.ts, src/ts/process/memory/hypav3.ts
Resolved the issue where the last user message was ignored during similarity search in the HypaV3 memory system due to equal weighting, and introduced an improved ranking algorithm using Convex Combination and RRF-inspired scoring.
In the existing system, equal weights were applied to the last 3 messages (e.g., User-AI-User), causing AI messages, which are typically longer and have more paragraphs, to dominate the similarity search, resulting in the last user message being ignored during retrieval.
1. **Temporal differential weighting**: Assign higher weights to recent messages using `(index + 1) / recentChats.length`
2. **Sub-query normalization (Exp only)**: Divide weights by the number of paragraphs in each message to mitigate length-based bias
3. **Multi-stage ranking**: Apply …
=> fix(hypav3): enhance memory retrieval

src/lang/en.ts, src/lib/Setting/Pages/AdvancedSettings.svelte, src/ts/process/request/google.ts, src/ts/process/request/openAI.ts, src/ts/storage/database.svelte.ts
---
This PR significantly improves the overall experience (MCP) for Google and OpenAI requests, continuing the work from PR https://github.com/kwaroran/RisuAI/pull/927. 
It resolves critical issues related to tool usage logs and context in OpenAI, fixes response streaming for Google requests, and enables simultaneous use of tools with streaming for both Google and OpenAI. Additionally, new options have been introduced in the advanced settings to enhance user control over tool display and logging.
*   **OpenAI Tool Log & Context Correction:** Previously, tool usage logs in OpenAI requests were incorrectly placed at the start of the response, rather than their actual position within the conversation flow. Furthermore, these logs only showed the final model text response, instead of the …
=> feat: Improve Google/OpenAI request experience with tool use, including response streaming

src/ts/model/modellist.ts
Add support for the stable release of Gemini 2.5 Pro (`gemini-2.5-pro`) which is currently missing from the model list.
=> Add gemini 2.5 pro stable

src/ts/globalApi.svelte.ts
Previously, DB backups accumulated infinitely on Tauri/Node environments due to the account sync cleanup logic being skipped when sync was enabled. 
Since account sync is unavailable on Tauri/Node, this caused backup files to grow without limit. 
Fixed by ensuring backup cleanup runs on these platforms regardless of sync settings.
=> fix: prevent infinite backup accumulation on Tauri/Node

src/ts/process/request/google.ts
Previously, Google API requests would return empty text responses when content was censored or blocked by safety filters, making it difficult for users to understand what went wrong.
Now empty responses are treated as request failures, which:
- Provides clear error messages for debugging
- Enables automatic retry logic to potentially resolve issues
- Gives users better visibility into why their request failed
=> fix: handle empty response on google request

src/ts/process/files/inlays.ts
Change inlay image resizing from max 1024px width/height to max 1024×1024 total pixels.
**Before:** Images resized if width OR height > 1024px
**After:** Images resized only if total pixels > 1,048,576
- Supports NovelAI default resolutions like 1216×832 without unnecessary downscaling
- Preserves aspect ratios while maintaining memory limits
- More flexible resolution support within pixel budget
- ✅ 1216×832 = 1,011,712 pixels (now allowed)
- ✅ 2048×512 = 1,048,576 pixels (now allowed)
- ❌ 2048×1024 = 2,097,152 pixels (still resized)
=> feat: use pixel-based resizing on writing inlay image

src/lib/ChatScreens/ChatBody.svelte
Fix translation state tracking issue in ChatBody component that prevented auto-translation from working properly.
Ensures that the 'translated' and 'retranslate' states are always tracked and reflected in the ChatBody UI.
=> fix: auto translation with 'cached message only' option

src/lib/ChatScreens/Chat.svelte
Hello!
This PR adds `data-chat-id` attributes to each chat message element.
Using only the chat index can be unclear for plugins or external tools that need to work with a specific chat message.
Exposing the unique `chatId` on the DOM element makes this identification much clearer and more reliable.
By adding these data attributes, plugins can now easily and safely get the unique `chatId` from the DOM element.
---
This is a small change, but I believe it will make it safer to implement plugins that interact with individual chat messages.
Let me know if you have any questions. Thank you!
=> feat: Add data attributes for chat id

src/lib/UI/ModelList.svelte
Added a back button to the top-left corner of the ModelList.
This resolves an issue on mobile devices where users were unable to navigate back on smaller screens due to a lack of clickable space.
=> Feat: Add Back Button to ModelList

src/ts/globalApi.svelte.ts
Optimized pargeChunks function to reduce time complexity from O(n²) to O(n) by converting the unpargeable array to a Set.
The "Checking Unnecessary Files..." step during app initialization was taking 10-100+ seconds for users with many assets due to quadratic time complexity
=> perf: optimize pargeChunks for faster app startup

src/lib/Others/HypaV3Modal.svelte, src/lib/Others/HypaV3Modal/modal-footer.svelte, src/lib/Others/HypaV3Modal/modal-header.svelte, src/lib/Others/HypaV3Modal/modal-summary-item.svelte, src/lib/Others/HypaV3Modal/types.ts, src/lib/Others/HypaV3Modal/utils.ts, src/ts/process/memory/hypav3.ts
- Extract summary item logic into separate ModalSummaryItem component.
- Fix bind:this reference corruption when deleting summary items
- Rename interfaces for clarity (SummaryUI → SummaryItemState)
=> fix(hyapv3): extract ModalSummaryItem and resolve DOM reference issues

README.md, docker-compose.yml
Hi there.
- Update README.md to run without the git pull process, as the 'latest' tag is now available.
- Modify docker-compose.yml to prevent the stack name from the device name.
For your information, Windows(after april 2018 update) also supports curl.
=> ci: use pre-built image from ghcr instead of build

src/lib/Setting/Pages/PersonaSettings.svelte
This pull request fixes the non-functional persona import button found in the persona list. The button now correctly opens the file dialog and imports the selected persona, restoring its intended behavior.
=> Fix: Restore Persona Import Functionality

src/lib/ChatScreens/Chat.svelte
Fixed an issue where adding chat id data to the chat block caused errors when the characters array was empty or when rendering the first message, due to poor `undefined` handling. 
This prevented entering the chat screen.
=> fix: chat id data error

src/lib/SideBars/Scripts/TriggerList2.svelte
Fixed a bug where the long-press gesture on mobile devices would trigger the reordering feature instead of opening the context menu.
This PR disables the reordering functionality specifically for mobile environments, allowing the long-press to correctly open the context menu. Desktop functionality is not affected.
=> Fix: Resolve long-press conflict on mobile

src/lib/Setting/Pages/AdvancedSettings.svelte
The import of the Node.js "inspector" (which was unnecessary) module caused a runtime error when running `pnpm dev` in the browser environment, as this module is not available outside of Node.js.
=> fix: remove `inspector` import for brower compatibility

src/ts/process/request/google.ts
This commit fixes a bug where requests for custom models using the Google format were sent with a hardcoded global key and a malformed URL that was missing the model name.
=> Fix: Incorrect request for custom models with Google format

server/node/server.cjs
Resolves double decoding errors on the Node.js server to fix access to Risu Hub, enabling user login and bot downloads.
=> fix: Risu hub access from node server

server/node/server.cjs
- Partially resolve PayloadTooLargeError: request entity too large in heavy chat environments
- express.json() and express.raw() limits raised: 50MB → 100MB
- Adjusted to match Cloudflare Reverse Proxy/Tunnel Free & Pro plan max upload size (100MB)
=> Increase payload size limit to 100MB

src/ts/process/triggers.ts
Resolves TypeScript compilation errors in TriggerData.svelte by adding the missing runAxLLM type to the triggerEffectV1 union type.
- Added  to the  type definition in 
- This fixes TypeScript errors where  was referenced but not included in the type union
- TypeScript compilation errors in TriggerData.svelte are now resolved
- The runAxLLM trigger effect type is now properly recognized
=> Fix: Add missing runAxLLM type to trigger effects

src/ts/cbs.ts
The picture above shows the current bug.
=> fix: Cbs random, pick Bug where the first element cannot be picked

server/node/server.cjs, src/ts/storage/accountStorage.ts
This pull request resolves several critical issues related to the Node.js proxy server, ensuring more stable and reliable communication with backend services.
Key Changes:
* Handles 303 Redirects Gracefully (`17c8738f`): The proxy server now properly follows 303 See Other redirects on the server-side. This prevents redirect responses from being sent directly
to the client, which previously caused JSON parsing errors when the client expected a data response but received an HTML redirect page instead.
* Fixes Content-Type and Body-Parsing Errors (`7809f262`):
* Correctly sets the Content-Type to application/octet-stream for binary data uploads, preventing 400 Bad Request errors from body-parser.
* Adds express.text() middleware to handle text/plain request bodies, resolving Cloudflare …
=> fix: Stabilize Hub Proxy by resolving redirect and request body errors

.github/workflows/docker-build.yml
- ghcr test finished(https://github.com/Acet-Aminophen/RisuAI/actions/runs/16644870206)
Hi there.
This commit resolves the error prints 'ERROR: failed to build: Multi-platform build is not supported for the docker driver.'
=> fix(ci) : buildx required error

src/ts/persona.ts, src/ts/pngChunk.ts
Refactors the PNG file reading process to improve performance, especially for large files on mobile devices.
- In `persona.ts`, replaces the synchronous `PngChunk.read` with the asynchronous `PngChunk.readGenerator` to avoid blocking the main thread during persona imports.
- In `pngChunk.ts`, the `readGenerator` is updated to use the `File.stream()` API. This provides a more efficient way to read local files, reducing memory overhead and processing time compared to the previous `File.slice()` and `FileReader` implementation.
=> perf: Improve performance of PNG card imports

src/lib/UI/GUI/MultiLangInput.svelte
- Fixes issue where valid 2-character language names (like Chinese '中文') were filtered out
=> Fix:display valid languages in creator's comment

src/ts/parser.svelte.ts, src/ts/process/files/inlays.ts
Migrated inlay assets storage from base64 strings to Blobs for significant performance improvements in memory usage and rendering speed.
- Rendering Speed: ~80-90% faster rendering for multiple inlay assets
- Memory Usage: ~30% reduction in memory consumption
- Blob URL Caching: Eliminates redundant URL generation for same assets
- Storage Migration: Base64 data URI → Blob-based storage
- Lazy Migration: Automatic conversion of existing string data to Blobs **on access**
- Dual API `getInlayAsset` and `getInlayAssetBlob`: Maintains backward compatibility while providing optimized Blob access
=> perf: optimize inlay asset with blob-based storage
